### ISSUE TITLE
see opened issues on a project

### ISSUE THREAD

**Issue by idell** [idell/GitLabConnect#2]
given
	a git repository stored on GitLab
when
	a user opens the project in IntelliJ
then 
	he would like to see the opened issues on the project

**Comment by kmos** [comment]
for the sake of simplicity, in order to achve th

**Comment by kmos** [comment]
for the sake of simplicity, we can save in some env variable user information in order to connect to the gitlab project. We can open an issue about it

**Comment by idell** [comment]
> for the sake of simplicity, we can save in some env variable user information in order to connect to the gitlab project. We can open an issue about create a menu for user info

Totally agree. 
As first I'd like to see the a tab with at least the issue title. As second step, this should be configurable with the user gitlab account.
